# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildSite
    steps:
    - checkout: self
      submodules: true
      clean: true
      persistCredentials: true
    - script: |
        cd ~
        wget https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.deb
        sudo dpkg -i hugo*.deb
      displayName: 'Install Hugo'
    - script: |
        hugo --log -v
      displayName: 'Generate Blog'
    - script: |
        cd public
        git add .
        git commit -m "rebuilding site $(Build.BuildId)"
        git push origin master
      displayName: 'Generate Blog and push'
    - script: |
        git add .
        git commit -m "Pushing changes from build $(Build.BuildId)"
        git push
      displayName: Committing changes in project
