# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildid: $(Build.BuildId)

jobs:
  - job: BuildSite
    steps:
    - checkout: self
      submodules: true
      clean: true
      persistCredentials: true
    - script: |
        cd ~
        wget https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.deb
        sudo dpkg -i hugo*.deb
      displayName: 'Install Hugo'
    - script: |
        hugo --log -v
      displayName: 'Generate Blog'
    - script: |
        git config user.email "hartmannr76@gmail.com"
        git config user.name "Ricky Hartmann"
        git add -A
        git commit -m "rebuilding site $(buildid)"
        git push origin master
      workingDirectory: ./public
      displayName: 'Committing changes in ./public folder'
