# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'



jobs:
  - job: BuildSite
    steps:
    - checkout: self
      submodules: true
      clean: true
      persistCredentials: true
    - script: sudo apt-get install hugo
      displayName: 'Install Hudo'
    - script: hugo version
