# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildSite
    steps:
    - checkout: self
      submodules: true
      clean: true
      persistCredentials: true
    - script: sudo apt-get install hugo
      displayName: 'Install Hugo'
    - script: |
        hugo --log -v
      displayName: 'Generate Blog'
    - script: |
        cd public
        git add .
        git commit -m "rebuilding site $(BuildID)"
        git push origin master
      displayName: 'Generate Blog and push'
    - script: |
        git add .
        git commit -m "Pushing changes from build $(BuildID)"
        git push
      displayName: Committing changes in project
